CREATE TABLE plan_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50)                              NOT NULL UNIQUE,
    CONSTRAINT pk_plan_type PRIMARY KEY (id)
);

INSERT INTO plan_type (code)
VALUES ('BASIC'),
       ('PREMIUM'),
       ('GROUP');

