INSERT INTO membership_plan (id,
                             version,
                             gym_id,
                             plan_type_id,
                             name,
                             price,
                             currency,
                             duration_months,
                             max_members,
                             active_members)
VALUES ('7f1c7b8d-8f53-4f47-a4bf-7c2e08c2d9c4',
        0,
        '550e8400-e29b-41d4-a716-446655440001',
        (SELECT id FROM plan_type WHERE code = 'BASIC'),
        'Morning BASIC',
        49.99,
        'EUR',
        3,
        20,
        0);
